### ISSUE TITLE
Support languages other than Python

### ISSUE THREAD

**Issue by krassowski** [jtpio/jupyterlab-codeium#2]
Just taking a quick glance on the code, it looks like a few options are hard-coded:

https://github.com/jtpio/jupyterlab-codeium/blob/a6bf19995f4e06e8659208d89f9b595e6aab3335/src/codeium.ts#L52-L56

FYI you can infer the language from the [`CompletionHandler.IRequest.mimeType`](https://jupyterlab.readthedocs.io/en/4.1.x/api/interfaces/completer.CompletionHandler.IRequest.html#mimeType) by passing it to [`languageRegistry.findByMIME()`](https://jupyterlab.readthedocs.io/en/stable/api/classes/codemirror.EditorLanguageRegistry-1.html#findByMIME)

**Comment by jtpio** [comment]
Thanks @krassowski!

Yes this should definitely be fixed. There might be a few other places where things could also be improved (this is still in a very early state).
